name: NEM
dependencies:
  - python=3.7
  - numpy==1.19.5
  - pytorch==1.9.0
  - pip==21.2.4
  - pip:
    - qiskit==0.23.0
    - tensorboard==2.6.0
    - pyscf==1.7.3
    - h5py==2.10
    - matplotlib==3.4.3
